---
- name: Updating  system
  apt:
    update_cache: yes

- name: Create user 
  user:
    name: prometheus
    create_home: no
    shell: "/usr/sbin/nologin"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/prometheus'
    - '/etc/prometheus'
    - '/var/lib/prometheus'

- name: Downlnload files
  retries: 5
  delay: 2
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz
    dest: /tmp/prometheus
    creates: /tmp/prometheus/prometheus-2.36.2.linux-amd64
    remote_src: yes

- name: Copy files
  copy:
    src: /tmp/prometheus/prometheus-2.36.2.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'prometheus', 'promtool' ]

- name: Copy Conf files 
  copy:
    src: /tmp/prometheus/prometheus-2.36.2.linux-amd64/{{ item }}
    dest: /etc/prometheus/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'console_libraries', 'consoles' ]

- name: Copy conf file 
  template:
    src=templates/prometheus.yml 
    dest=/etc/prometheus/

- name: Create file 
  template:
    src=templates/prometheus.service
    dest=/etc/systemd/system/
  notify:
    - systemd reload

- name: Start
  systemd:
    name: prometheus
    state: started
    enabled: yes