- name: Create the Alertmanager group
  ansible.builtin.group:
    name: "{{ alertmanager_group }}"
    system: true

- name: Create the Alertmanager user
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: true
    createhome: false

- name: Make sure the Alertmanager install directory exists
  ansible.builtin.file:
    dest: "{{ alertmanager_install_path }}/alertmanager"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Download Alertmanager
  ansible.builtin.unarchive:
    src: "{{ alertmanager_release_url }}"
    dest: "{{ alertmanager_install_path }}/alertmanager"
    creates: "{{ alertmanager_install_path }}/alertmanager/alertmanager.yml"
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Symlink the Alertmanager binaries
  ansible.builtin.file:
    src: "{{ alertmanager_install_path }}/alertmanager/{{ item }}"
    dest: "{{ alertmanager_bin_path }}/{{ item }}"
    state: link
  notify: restart alertmanager
  with_items:
    - alertmanager
    - amtool

- name: Create the Alertmanager Storage directory
  ansible.builtin.file:
    name: "{{ alertmanager_storage_path }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0755

- name: Create the Alertmanager configuration directory
  ansible.builtin.file:
    name: "{{ alertmanager_config_path }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0755

- name: Create the Alertmanager templates directory
  ansible.builtin.file:
    name: "{{ alertmanager_templates_path }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0755

- name: Create the Alertmanager configuration file
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_path }}/{{ alertmanager_config_file }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0640
    validate: "{{ alertmanager_bin_path }}/amtool check-config %s"
  notify: reload alertmanager

- name: Create the Systemd Unit file for the Alertmanager service
  ansible.builtin.template:
    src: alertmanager.systemd.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0640
  notify: restart alertmanager

- name: service always started
  ansible.builtin.systemd:
    name: alertmanager
    state: started
    enabled: true
