---
- name: Updating  system
  apt:
    update_cache: yes

- name: Create user 
  user:
    name: grafana
    create_home: no
    shell: "/usr/sbin/nologin"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: grafana
    group: grafana

- name: Downlnload files
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_9.0.7_amd64.deb
    dest: '/tmp/grafana'

- name: Install 
  apt:
    deb: '/tmp/grafana/grafana_9.0.7_amd64.deb' 

- name: setup conf
  template:
    src: templates/provisioning/dashboards/dashboard.yml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yml

- name: setup conf
  template:
    src: templates/provisioning/datasources/datasource.yml
    dest: /etc/grafana/provisioning/datasources/datasource.yml


- name: Add directory
  file:
    path: /var/lib/grafana/dashboards
    recurse: yes
    state: directory

- name: Start
  systemd:
    name: grafana-server
    state: started
    enabled: yes